// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1752193771);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1752193771);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{435ef077-b00e-44c7-aec2-46f0adcbe3c6}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1752193768);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 143);
user_pref("browser.newtabpage.activity-stream.impressionId", "{52541e5b-8625-4dcd-b56f-d4e8040fd571}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1752193769);
user_pref("browser.search.region", "KR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1752193770");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240419214016");
user_pref("browser.startup.homepage_override.mstone", "125.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1752193769);
user_pref("browser.topsites.contile.lastFetch", 1752193770);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1752193770494");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "125.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "KR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20240419214016");
user_pref("extensions.lastAppVersion", "125.0.2");
user_pref("extensions.lastPlatformVersion", "125.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"80c02175-2b95-4234-a6ac-e359f41be5bf\",\"pictureinpicture@mozilla.org\":\"befc9d33-833a-4c2d-b56a-844b3facae1d\",\"screenshots@mozilla.org\":\"5c226385-277f-43f8-9572-2b2498f7e226\",\"webcompat-reporter@mozilla.org\":\"9ecb7f12-df4e-4a3b-bd71-d17918faff24\",\"webcompat@mozilla.org\":\"affb4ec9-4be8-4ba8-b00f-4ea8b2d4e7ff\",\"default-theme@mozilla.org\":\"375676b1-0ce9-4b35-a7a0-19372bf2702b\",\"addons-search-detection@mozilla.com\":\"b24ebe81-892e-4373-b876-fe348e802e38\",\"google@search.mozilla.org\":\"71e706fb-b198-425a-ae3e-e5d83b3f89a8\",\"wikipedia@search.mozilla.org\":\"2bef9d57-d5ce-4e5c-b611-b7bac68d72d7\",\"bing@search.mozilla.org\":\"28ecd18a-42be-48d9-ba61-a4d230e42c13\",\"ddg@search.mozilla.org\":\"488527e3-1a42-4d67-b8fa-6f5b0d57291c\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f5f17888-bb59-413e-99d9-6b672af43fe9");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1752193766);
user_pref("toolkit.telemetry.cachedClientID", "19950a75-7804-4dc3-951a-dccf8d7bb83b");
user_pref("toolkit.telemetry.previousBuildID", "20240419214016");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
